FROM golang:1.26.5-alpine AS builder

ENV CGO_ENABLED=0 \
    GOOS=linux

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . /app

RUN go build -ldflags="-w -s" -o migrate ./cmd/migrate

# ---------------------------------------------------------------------------- #

FROM alpine:3.21.3

WORKDIR /app

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/migrate /app/

ENTRYPOINT ["/app/migrate"]
